openapi: 3.0.0
info:
  title: Text Analyzer API
  version: 1.0.0
  description: API para análise de texto e detecção de sentimento
servers:
  - url: http://localhost:3000/api
paths:
  /analyze-text:
    post:
      summary: Analisa um texto e retorna estatísticas e sentimento
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - text
              properties:
                text:
                  type: string
                  example: "Este é um ótimo dia para programar!"
      responses:
        '200':
          description: Resultado da análise
          content:
            application/json:
              schema:
                type: object
                properties:
                  wordCount:
                    type: integer
                    example: 6
                  top5Words:
                    type: array
                    items:
                      type: object
                      properties:
                        word:
                          type: string
                          example: programar
                        count:
                          type: integer
                          example: 2
                  sentiment:
                    type: string
                    example: positivo
  /search-term:
    get:
      summary: Verifica se um termo está presente na última análise
      parameters:
        - in: query
          name: term
          schema:
            type: string
          required: true
          description: Termo a ser buscado
      responses:
        '200':
          description: Resultado da busca
          content:
            application/json:
              schema:
                type: object
                properties:
                  found:
                    type: boolean
                    example: true
